SHOW WAREHOUSES;

CREATE WAREHOUSE demo_warehouse
WITH
WAREHOUSE_SIZE = "X-small"
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = "Demo warehouse created through a worksheet";

SHOW WAREHOUSES;

-- Scaling up
ALTER WAREHOUSE COMPUTE_WH
SET AUTO_SUSPEND = 60;

--Scaling out
ALTER WAREHOUSE DEMO_WAREHOUSE
SET MAX_CLUSTER_COUNT = 3;

DROP WAREHOUSE DEMO_WAREHOUSE;

SHOW WAREHOUSES;